name: webapp-ciIcd

on:
  push:

jobs:
  ci_cd:
    runs-on: ubuntu:latest
    name: Super Linter

    steps:
      - name: Checks The Code
        uses: actions/checkout@v4

      - name: Run Super Linter
        uses: super-linter/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

tests:
  runs_on: ubuntu:latest
  name: Run and Test front and back ends

  steps:
    - name: Checks The Code
      uses: actions/checkout@v4

    - name: Node.js Setup
      uses: actions/setup-node@v4
      with:
        node-version: '18.19.1'

    - name:
      working-directory: 

      
